- name: Initialise Kubernetes Master
  hosts: T_R-k8s-master
  gather_facts: yes
  become: no
  remote_user: ubuntu
  tasks:
    - name: Copy deployment file to remote
      copy:
        src: "./scheduler.yml"
        dest: "~ubuntu/deploy.yml"
        mode: "644"
        owner: ubuntu
        group: ubuntu
    - name: Deploy Scheduler
      shell: kubectl apply -f ~ubuntu/deploy.yml
