- name: Add monitoring
  hosts: T_R-k8s-master
  gather_facts: no
  become: no
  remote_user: ubuntu
  tasks:
    - name: Upload manifests
      copy:
        src: "manifests"
        dest: "~/manifests/"
    - name: Apply manifests
      shell: kubectl apply -f ~/manifests/
    - pause:
        seconds: 5
    - name: Apply Prometheus deployment set for the second time to resolve async error
      shell: kubectl apply -f ~/manifests/
