apiVersion: v1
kind: ServiceAccount
metadata:
  name: custom-kube-scheduler
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: custom-kube-scheduler-as-kube-scheduler
subjects:
- kind: ServiceAccount
  name: custom-kube-scheduler
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: system:kube-scheduler
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    component: custom-kube-scheduler
    tier: control-plane
  name: custom-kube-scheduler
  namespace: kube-system
spec:
  serviceAccountName: custom-kube-scheduler
  containers:
  - command:
    - kube-scheduler
    - --config=/usr/local/lib/kube-scheduler/config.yml
    image: registry.gitlab.com/laitingsheng/scheduler-plugins/custom-kube-scheduler:0f3a041e
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10251
        scheme: HTTP
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: custom-kube-scheduler
    resources:
      requests:
        cpu: 500m
        memory: 2Gi
      limits:
        cpu: 1
        memory: 4Gi
  nodeName: t-r-k8s-minion-extra
  imagePullSecrets:
  - name: custom-scheduler-registry-secret
  hostNetwork: true
  priorityClassName: system-cluster-critical
